import type { OutputData } from "@editorjs/editorjs";
import type { ResumeFormDocument } from "./resume-form";

// Current editor surface still exposes write_up. Keep this list stable until the
// UI moves to the canonical generated-output tabs.
export const DOCUMENT_KINDS = ["resume", "write_up", "submission", "email"] as const;
export type DocumentKind = (typeof DOCUMENT_KINDS)[number];

// Stored cases retain the legacy write_up document and add loxo_update. Canonical
// capability runs are first-class records, not documents.
export const STORED_DOCUMENT_KINDS = [
  ...DOCUMENT_KINDS,
  "loxo_update",
] as const;
export type StoredDocumentKind = (typeof STORED_DOCUMENT_KINDS)[number];

export function isStoredDocumentKind(value: string): value is StoredDocumentKind {
  return (STORED_DOCUMENT_KINDS as readonly string[]).includes(value);
}

// Four source-grounded outputs generated by the after-call workflow. write_up
// remains a legacy editable document but is not a canonical generated output.
export const GENERATED_OUTPUT_KINDS = [
  "resume",
  "submission",
  "email",
  "loxo_update",
] as const;
export type GeneratedOutputKind = (typeof GENERATED_OUTPUT_KINDS)[number];
export type SaveState = "saved" | "saving" | "unsaved" | "failed";

export const SOURCE_KINDS = [
  "job_description",
  "resume",
  "transcript",
  "call_notes",
  "pasted_text",
  "other",
] as const;
export type SourceKind = (typeof SOURCE_KINDS)[number];

// Job folders are shared by every candidate case in the Job. Candidate-private
// evidence must never be accepted here or it can leak into another candidate's
// capability context.
export const JOB_SOURCE_KINDS = [
  "job_description",
  "call_notes",
  "pasted_text",
  "other",
] as const satisfies readonly SourceKind[];

export function isJobSourceKind(kind: SourceKind): kind is (typeof JOB_SOURCE_KINDS)[number] {
  return (JOB_SOURCE_KINDS as readonly SourceKind[]).includes(kind);
}

export const SOURCE_LIFECYCLE_STATUSES = [
  "uploaded",
  "parsed",
  "classified",
  "reviewed",
] as const;
export type SourceLifecycleStatus = (typeof SOURCE_LIFECYCLE_STATUSES)[number];

export type RoleRecord = { id: string; title: string; client: string | null; status: string };
export type CandidateRecord = { id: string; name: string; currentTitle: string | null };
export type FactStatus = "proposed" | "confirmed" | "conflicted" | "unavailable";
export type CandidateFact = { key: string; value: string | null; status: FactStatus; sourceId: string | null; confirmedAt: string | null };
export type SourceReviewRequirement = {
  id: string;
  sourceId: string;
  sourceRef: string;
  documentKind: "submission";
  previousKind: SourceKind;
  currentKind: SourceKind;
  reason: string;
  createdAt: string;
};
export type AssistantState = {
  missing: string[];
  askNext: string[];
  fitConcern: string;
  nextAction: string;
  reviewRequired?: SourceReviewRequirement[];
};
export type SubmissionDocument = {
  name: string; title: string; compensationTarget: string; currentCompensation: string;
  vacation: string; location: string; workStatus: string; interviewAvailability: string;
  startDateNotice: string; reasonForLeaving: string; profileSummary: string;
};
export type CaseDocument = { kind: StoredDocumentKind; revision: number; content: OutputData | string | SubmissionDocument | ResumeFormDocument | Record<string, unknown>; updatedAt: string };
export type DocumentVersion = {
  kind: StoredDocumentKind;
  revision: number;
  content: CaseDocument["content"];
  sourceRefs: string[];
  capabilityRunId: string | null;
  origin: "generated" | "edited";
  createdAt: string;
};
export type CaseSource = {
  id: string;
  kind: SourceKind;
  filename: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
  captureTime: string;
  lifecycleStatus: SourceLifecycleStatus;
  reviewStatus: "unreviewed" | "reviewed";
  parsedText: string | null;
  classificationMethod: "explicit" | "filename" | "content" | "manual" | "uncertain" | null;
};
export type JobSource = CaseSource & { roleId: string; contextStatus: "active" | "superseded" };
export type CandidateCase = {
  id: string; roleId: string; candidateId: string; status: string; notes: string;
  notesDrawingSvg: string; notesFont: string; notesSize: number; revision: number; facts: CandidateFact[];
  assistant: AssistantState; externalRefs: Record<string, string>;
  documents: Record<StoredDocumentKind, CaseDocument>; sources: CaseSource[]; updatedAt: string;
};
export type CandidateSourceIntakeResult = {
  candidate: CandidateRecord;
  candidateCase: CandidateCase;
  reused: boolean;
};
export type ConnectorCapability = { id: string; label: string; status: "available" | "not_connected" | "unsupported"; detail: string };
export type WorkspacePayload = {
  roles: RoleRecord[];
  candidates: CandidateRecord[];
  cases: CandidateCase[];
  jobSourcesByRoleId: Record<string, JobSource[]>;
  connectors: ConnectorCapability[];
};

export const EMPTY_RESUME: OutputData = { time: 0, version: "2.31.0", blocks: [] };
export const EMPTY_SUBMISSION: SubmissionDocument = {
  name: "", title: "", compensationTarget: "", currentCompensation: "", vacation: "",
  location: "", workStatus: "", interviewAvailability: "", startDateNotice: "",
  reasonForLeaving: "", profileSummary: "",
};
