import type { OutputData } from "@editorjs/editorjs";

// Current editor surface still exposes write_up. Keep this list stable until the
// UI moves to the canonical generated-output tabs.
export const DOCUMENT_KINDS = ["resume", "write_up", "submission", "email"] as const;
export type DocumentKind = (typeof DOCUMENT_KINDS)[number];

// Stored cases retain the legacy write_up document and add loxo_update. Nothing
// is renamed or discarded when an existing case is hydrated.
export const STORED_DOCUMENT_KINDS = [
  ...DOCUMENT_KINDS,
  "loxo_update",
] as const;
export type StoredDocumentKind = (typeof STORED_DOCUMENT_KINDS)[number];

// Four source-grounded outputs generated by the after-call workflow. write_up
// remains a legacy editable document but is not a canonical generated output.
export const GENERATED_OUTPUT_KINDS = [
  "resume",
  "submission",
  "email",
  "loxo_update",
] as const;
export type GeneratedOutputKind = (typeof GENERATED_OUTPUT_KINDS)[number];
export type SaveState = "saved" | "saving" | "unsaved" | "failed";

export const SOURCE_KINDS = [
  "job_description",
  "resume",
  "transcript",
  "call_notes",
  "pasted_text",
  "other",
] as const;
export type SourceKind = (typeof SOURCE_KINDS)[number];

export const SOURCE_LIFECYCLE_STATUSES = [
  "uploaded",
  "parsed",
  "classified",
  "reviewed",
] as const;
export type SourceLifecycleStatus = (typeof SOURCE_LIFECYCLE_STATUSES)[number];

export type RoleRecord = { id: string; title: string; client: string | null; status: string };
export type CandidateRecord = { id: string; name: string; currentTitle: string | null };
export type FactStatus = "proposed" | "confirmed" | "conflicted" | "unavailable";
export type CandidateFact = { key: string; value: string | null; status: FactStatus; sourceId: string | null; confirmedAt: string | null };
export type AssistantState = { missing: string[]; askNext: string[]; fitConcern: string; nextAction: string };
export type SubmissionDocument = {
  name: string; title: string; compensationTarget: string; currentCompensation: string;
  vacation: string; location: string; workStatus: string; interviewAvailability: string;
  startDateNotice: string; reasonForLeaving: string; profileSummary: string;
};
export type CaseDocument = { kind: StoredDocumentKind; revision: number; content: OutputData | string | SubmissionDocument; updatedAt: string };
export type CaseSource = {
  id: string;
  kind: SourceKind;
  filename: string;
  contentType: string;
  sizeBytes: number;
  sha256: string;
  captureTime: string;
  lifecycleStatus: SourceLifecycleStatus;
  reviewStatus: "unreviewed" | "reviewed";
  parsedText: string | null;
  classificationMethod: "explicit" | "filename" | "content" | "manual" | "uncertain" | null;
};
export type CandidateCase = {
  id: string; roleId: string; candidateId: string; status: string; notes: string;
  notesFont: string; notesSize: number; revision: number; facts: CandidateFact[];
  assistant: AssistantState; externalRefs: Record<string, string>;
  documents: Record<StoredDocumentKind, CaseDocument>; sources: CaseSource[]; updatedAt: string;
};
export type ConnectorCapability = { id: string; label: string; status: "available" | "not_connected" | "unsupported"; detail: string };
export type WorkspacePayload = { roles: RoleRecord[]; candidates: CandidateRecord[]; cases: CandidateCase[]; connectors: ConnectorCapability[] };

export const EMPTY_RESUME: OutputData = { time: 0, version: "2.31.0", blocks: [] };
export const EMPTY_SUBMISSION: SubmissionDocument = {
  name: "", title: "", compensationTarget: "", currentCompensation: "", vacation: "",
  location: "", workStatus: "", interviewAvailability: "", startDateNotice: "",
  reasonForLeaving: "", profileSummary: "",
};
